services:
  postgres:
    image: postgres:16
    container_name: aimarket-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: aimarket
      POSTGRES_USER: aimarket_user
      POSTGRES_PASSWORD: aimarket_pass
    ports:
      - "5433:5432"
    volumes:
      - aimarket_postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: aimarket-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  aimarket_postgres_data:
